inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake
AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false